### ISSUE TITLE
页码问题，第一张图片和第二张图片的index均为0

### ISSUE THREAD

**Issue by yujieace** [kejinlu/KKPagedFlowView#18]
实现-(void)flowView:(PagedFlowView *)flowView didTapPageAtIndex:(NSInteger)index
后，当点击第一张图和第二张图的时候，其返回的index值均为0，第三张图片的index为1，第四张为2，也就是第一张的index可能为负值。

**Comment by kejinlu** [comment]
我测试了下 没发现这种情况，有特殊的场景么？

**Comment by kejinlu** [comment]
你再试试，代码有更新

**Comment by yujieace** [comment]
谢谢，之前为了解决这个问题写了自定义了Imageview，解决了问题。近期再试一下新的版本。
